version: "3"

services:
  api:
    image: ruby:2.5-alpine
    environment:
      # Setting the response body as an environment variable is just a way
      # to get around the multiple layers of nested quotes in the command!
      RESPONSE_BODY: "{\"id\": \"1\", \"name\": \"Foo\"}"
    command: sh -c "gem install rack && rackup -o 0.0.0.0 -b \"run ->(env){ [200, {'Content-Type' => 'application/json'}, [ENV['RESPONSE_BODY']]] }\""
    expose:
      - "9292"

  pact_verifier:
    image: pactfoundation/pact-cli:latest
    depends_on:
      - api
    environment:
      - PACT_BROKER_BASE_URL=http://host.docker.internal
      - PACT_BROKER_USERNAME=user
      - PACT_BROKER_PASSWORD=secret
      - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
      - GIT_COMMIT=fake-git-sha-for-demo$(date +%s)
    command: >
      verify
      --provider-base-url http://host.docker.internal:8000
      --provider Bar
      --provider-app-version ${GIT_COMMIT}
      --provider-version-tag master
      --wait 10
